version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - db-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
